language: go

go:
  - 1.9.2

install: 
  - go get -u github.com/kardianos/govendor
  - cd $HOME/gopath/src/github.com/thechunk/go-roam-server && govendor sync

deploy:
  provider: heroku
  api_key:
    secure: Sk+AuI34u8eXX6PrPwYd2t3nXSsZioNi6pYD0Z7lAiYNi23HRHfckfkFLP9ECivoTzWgcg0k4JuT/vcPCVw9JEhO35XvOS7jCUy2JM2CwUAphUcVxaXhyQPUugIv3ZYjhmCoeX6525WUYtL7z4j5Du7B/RhMlWVHTm/ERdi3QeA0ehj+3l2TxKr4hlARZiNbpkYOZWfKYRNhtYfwI7C812d7Q26EDvOlCkLKbS2A8SIU48yqUlHqFQphmUXxOLXyoYh22TTeSiMl0YpOyQjxBDLiva+arLIYS/34XNugLt7GVOgqRLxPQBERYYohTaKsD6kB76qSNa5XCpWEyV3EPUmqZVm2VGzvlTDhqPRE2Bhe2MSDukPppHVHtGlheRx7hrt5no1XUVYYxZoDSPtGZsR77ras4vkiAmU6bsk3WqZfbjtscL4YjZuBfJn3pgdLc9ExpX+h76hcaAGrZMVL5FQxIP+7j74LY55tEvWxIhNfjPyLJmYRBT2pdJbkK19D1FC16vgroywdMewUowJVDTqLEwML0L8Wh2NWnwdd8sC5KkVPAc5E3dZFS8le2seQilsb9yNZdOAmZ8GS7PBVSm+Kpx4ebrWupxQtKv/ZTeQpWIVAWKOJ+rUusxYAYazO7L2FKNXmWBF0LEA9h6noOv0X1NfakLdra8ZWOcmNwAM=
  app: roam-server
